// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"github.com/tupyy/tinyedge-controller/internal/entity"
	"sync"
)

// Ensure, that DeviceReaderMock does implement DeviceReader.
// If this is not the case, regenerate this file with moq.
var _ DeviceReader = &DeviceReaderMock{}

// DeviceReaderMock is a mock implementation of DeviceReader.
//
//	func TestSomethingThatUsesDeviceReader(t *testing.T) {
//
//		// make and configure a mocked DeviceReader
//		mockedDeviceReader := &DeviceReaderMock{
//			GetDeviceFunc: func(ctx context.Context, id string) (entity.Device, error) {
//				panic("mock out the GetDevice method")
//			},
//		}
//
//		// use mockedDeviceReader in code that requires DeviceReader
//		// and then make assertions.
//
//	}
type DeviceReaderMock struct {
	// GetDeviceFunc mocks the GetDevice method.
	GetDeviceFunc func(ctx context.Context, id string) (entity.Device, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDevice holds details about calls to the GetDevice method.
		GetDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
	}
	lockGetDevice sync.RWMutex
}

// GetDevice calls GetDeviceFunc.
func (mock *DeviceReaderMock) GetDevice(ctx context.Context, id string) (entity.Device, error) {
	if mock.GetDeviceFunc == nil {
		panic("DeviceReaderMock.GetDeviceFunc: method is nil but DeviceReader.GetDevice was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetDevice.Lock()
	mock.calls.GetDevice = append(mock.calls.GetDevice, callInfo)
	mock.lockGetDevice.Unlock()
	return mock.GetDeviceFunc(ctx, id)
}

// GetDeviceCalls gets all the calls that were made to GetDevice.
// Check the length with:
//
//	len(mockedDeviceReader.GetDeviceCalls())
func (mock *DeviceReaderMock) GetDeviceCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetDevice.RLock()
	calls = mock.calls.GetDevice
	mock.lockGetDevice.RUnlock()
	return calls
}
