// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package configuration

import (
	"context"
	"github.com/tupyy/tinyedge-controller/internal/entity"
	"sync"
)

// Ensure, that ManifestReaderMock does implement ManifestReader.
// If this is not the case, regenerate this file with moq.
var _ ManifestReader = &ManifestReaderMock{}

// ManifestReaderMock is a mock implementation of ManifestReader.
//
//	func TestSomethingThatUsesManifestReader(t *testing.T) {
//
//		// make and configure a mocked ManifestReader
//		mockedManifestReader := &ManifestReaderMock{
//			GetManifestFunc: func(ctx context.Context, ref entity.ManifestReference) (entity.ManifestWork, error) {
//				panic("mock out the GetManifest method")
//			},
//		}
//
//		// use mockedManifestReader in code that requires ManifestReader
//		// and then make assertions.
//
//	}
type ManifestReaderMock struct {
	// GetManifestFunc mocks the GetManifest method.
	GetManifestFunc func(ctx context.Context, ref entity.ManifestReference) (entity.ManifestWork, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetManifest holds details about calls to the GetManifest method.
		GetManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref entity.ManifestReference
		}
	}
	lockGetManifest sync.RWMutex
}

// GetManifest calls GetManifestFunc.
func (mock *ManifestReaderMock) GetManifest(ctx context.Context, ref entity.ManifestReference) (entity.ManifestWork, error) {
	if mock.GetManifestFunc == nil {
		panic("ManifestReaderMock.GetManifestFunc: method is nil but ManifestReader.GetManifest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref entity.ManifestReference
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockGetManifest.Lock()
	mock.calls.GetManifest = append(mock.calls.GetManifest, callInfo)
	mock.lockGetManifest.Unlock()
	return mock.GetManifestFunc(ctx, ref)
}

// GetManifestCalls gets all the calls that were made to GetManifest.
// Check the length with:
//
//	len(mockedManifestReader.GetManifestCalls())
func (mock *ManifestReaderMock) GetManifestCalls() []struct {
	Ctx context.Context
	Ref entity.ManifestReference
} {
	var calls []struct {
		Ctx context.Context
		Ref entity.ManifestReference
	}
	mock.lockGetManifest.RLock()
	calls = mock.calls.GetManifest
	mock.lockGetManifest.RUnlock()
	return calls
}
