---
name: Go
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang:1.20-buster

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
   
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install --yes --no-install-recommends postgresql-client

    - name: setup pg
      run: | 
        chmod 600 sql/.pgpass
        DB_HOST=postgres DB_PORT=5432 make postgres.setup

    - name: Test
      run: POSTGRES_HOST=postgres POSTGRES_PORT=5432 make test

    - name: Checking generated files are up to date
      run: |
        if [[ $(git ls-files --others --exclude-standard) ]]; then git ls-files --others --exclude-standard; echo "These files are not tracked by git"; exit 1; fi
        if [ -n "$(git status --porcelain)" ]; then echo "There are uncommitted changes:"; git status --short; exit 1; fi

